### ISSUE TITLE
Got an error after restart server: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization java.lang.IllegalArgumentException: unknown world

### ISSUE THREAD

**Issue by A1erice** [derfurkan/RegionTitles#1]
First of all, i want to say thank you for creating such a useful plugin. I just used your plugin yesterday and it worked perfectly amazing! However, the plugin got an error and it keep looping this on my console after restarting my server. Do you mind giving me some spare time to help me fix this problem? I would be very appreciating for your help. Thank you!
[log.txt](https://github.com/derfurkan/RegionTitles/files/12064299/log.txt)

**Comment by derfurkan** [comment]
### Hey thank you for reporting an issue and showing that you want to make the plugin better.

I investigated the issue and it seems like the plugin still uses the 1.18 API Calls which are not supported in newer versions.
So i decided to push a update to SpigotMC with 1.20.1 API Support. If this wont fix you issue reopen the issue.
Here is the update: https://www.spigotmc.org/resources/regiontitles-create-titles-based-on-regions.109137/update?update=509036

**Comment by A1erice** [comment]
I'm very appreciate your hard-working. Unfortunately, the issue still remains. 
[log.txt](https://github.com/derfurkan/RegionTitles/files/12067543/log.txt)
I also sorry for not give you the fully error on the console. I just realized there are more. I hope you will find some useful information in here. Have a good day!

**Comment by derfurkan** [comment]
> I'm very appreciate your hard-working. Unfortunately, the issue still remains. [log.txt](https://github.com/derfurkan/RegionTitles/files/12067543/log.txt) I also sorry for not give you the fully error on the console. I just realized there are more. I hope you will find some useful information in here. Have a good day!

Well i think this issues is coming either from Purpur or the server running on an not-supported version.
I would recommend to update or try again without Purpur. The logs indicate that RegionTitles is trying to use an function created by the server. If the server wont offer that function it will throw that error.

**Comment by A1erice** [comment]
Thank you for speeding time for me. My server strongly depends on purpur currently so I think I cannot use your plugin right now. I hope that I can use and support your plugin on the others server in the future. Again, thank you for helping me on this issue!
